<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Korp.Invoicing.Application\Korp.Invoicing.Application.csproj" />
        <ProjectReference Include="..\Korp.Invoicing.Domain\Korp.Invoicing.Domain.csproj" />
    </ItemGroup>

</Project>
